const products = [
  {
    id: 1,
    name: "Бузинная палочка",
    price: 5000,
    required_level: 3,
    delivery_type: "OWL",
    category_id: 8,
    image_url: "/images/wand.png",
    shop_id: 1,
  },
  {
    id: 2,
    name: "Амортенция",
    price: 700,
    required_level: 5,
    delivery_type: "OWL",
    category_id: 1,
    image_url: "/images/potion.png",
    shop_id: 2,
  },
  {
    id: 3,
    name: "Учебник заклинаний",
    price: 300,
    required_level: 1,
    delivery_type: "PIGEON",
    category_id: 3,
    image_url: "/images/book.png",
    shop_id: 3,
  },
  {
    id: 4,
    name: "Нимбус 2000",
    price: 400,
    required_level: 2,
    delivery_type: "OWL",
    category_id: 5,
    image_url: "/images/broom.png",
    shop_id: 4,
  },
  {
    id: 5,
    name: "Сова-почтальон",
    price: 200,
    required_level: 1,
    delivery_type: "OWL",
    category_id: 7,
    image_url: "/images/owl.png",
    shop_id: 5,
  },
  {
    id: 6,
    name: "Мантия-невидимка",
    price: 10000,
    required_level: 7,
    delivery_type: "PHOENIX",
    category_id: 6,
    image_url: "/images/cloak.png",
    shop_id: 6,
  }
];
